### ISSUE TITLE
confused about the state of project 3

### ISSUE THREAD

**Issue by scott2b** [tommeagher/pycar14#22]
I'm not quite sure I am looking at the official version of the repository, and am a bit confused about what is expected for project no. 3.

I was going through this with the understanding that there was a narrative readme intro to scraping with BeautifulSoup and then 2 additional json/csv related project files (get_json, json_to_csv)

Now I am just seeing the Readme and a scraper file, which seems like an exercise file of the same info in the Readme file. Could I get an update on what is generally expected for project 3? Thanks.

**Comment by tommeagher** [comment]
@scott2b, this is not the repo you're looking for. This is from the first iteration of the class two years ago. The one you want is [here](https://github.com/ireapps/pycar/tree/master/project3).
