### ISSUE TITLE
training suggestion

### ISSUE THREAD

**Issue by mjwebster** [tommeagher/pycar14#23]
I think it would help beginners a lot if you named variables in a way that makes it much easier to see what's a variable and what's not. For example, something like "vrow" or "vfilename" or "varfilename" or "var_row". Anything that sets them apart from everything else. It gets confusing when you have a variable named "writer' and then a command that includes "writer" and stuff like that.

**Comment by tommeagher** [comment]
Moved this discussion to the new project repo in ireapps/pycar#37
